[project]
name = "hw-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.3",
    "requests>=2.32.5",
    "scikit-learn==1.6.1",
    "unicorn>=2.1.4",
    "uvicorn>=0.38.0",
]
